[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Force Rollup to use JavaScript instead of native binaries
  ROLLUP_FORCE_JS = "true"
  # Additional Rollup environment variables
  ROLLUP_WATCH = "false"
  # Specify Node.js version for Vite compatibility (requires 20+)
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
